import { Area, Route, User, Sponsor } from "./types";

// NOTE: This is the legacy/simple seed. 
// The authoritative rich hierarchical seed lives at: lib/data/seed-data.ts
// (8 areas with full hierarchy, 25 famous routes, photos, ticks, condition reports, full provenance)

export const AREAS: Area[] = [
  {
    id: "yose",
    name: "Yosemite Valley",
    parent: "Yosemite National Park",
    country: "USA",
    lat: 37.7459,
    lng: -119.5936,
    description: "The birthplace of big wall climbing. Granite paradise.",
    bestSeason: "Apr–Oct (avoid summer crowds)",
    sources: ["openbeta", "mountainproject"],
    routeCount: 1200,
    photoUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&q=80",
  },
  {
    id: "redrocks",
    name: "Red Rock Canyon",
    parent: "Las Vegas, NV",
    country: "USA",
    lat: 36.1608,
    lng: -115.4689,
    description: "World-class sandstone sport & trad in stunning desert.",
    bestSeason: "Oct–Apr",
    sources: ["openbeta", "mountainproject"],
    routeCount: 2800,
    photoUrl: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=1200&q=80",
  },
  {
    id: "squamish",
    name: "Squamish",
    parent: "British Columbia",
    country: "Canada",
    lat: 49.7016,
    lng: -123.1558,
    description: "Granite cracks, boulders, and the Chief. Paradise for trad climbers.",
    bestSeason: "May–Sep",
    sources: ["openbeta", "thecrag"],
    routeCount: 1400,
    photoUrl: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1200&q=80",
  },
  {
    id: "font",
    name: "Fontainebleau",
    parent: "France",
    country: "France",
    lat: 48.4105,
    lng: 2.7006,
    description: "The world capital of bouldering. Sandstone magic.",
    bestSeason: "Mar–Nov",
    sources: ["openbeta", "thecrag"],
    routeCount: 30000,
    photoUrl: "https://images.unsplash.com/photo-1527004013197-933c4bb611b3?w=1200&q=80",
  },
  {
    id: "kalymnos",
    name: "Kalymnos",
    parent: "Greece",
    country: "Greece",
    lat: 36.9955,
    lng: 26.9385,
    description: "Tufas, pockets, and sea views. Sport climbing heaven.",
    bestSeason: "Apr–Oct",
    sources: ["thecrag"],
    routeCount: 3200,
    photoUrl: "https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=1200&q=80",
  },
  {
    id: "indiancreek",
    name: "Indian Creek",
    parent: "Utah",
    country: "USA",
    lat: 38.0214,
    lng: -109.5498,
    description: "The crack climbing capital of the world. Perfect splitter granite.",
    bestSeason: "Mar–May & Sep–Nov",
    sources: ["openbeta", "mountainproject"],
    routeCount: 900,
    photoUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&q=80",
  },
];

export const ROUTES: Route[] = [
  // YOSEMITE
  {
    id: "r1",
    name: "The Nose",
    areaId: "yose",
    areaName: "Yosemite Valley",
    grade: "5.14a",
    type: "Trad",
    lengthFt: 2900,
    pitches: 31,
    protection: "Nuts, cams to #4, many fixed pins",
    fa: "Warren Harding 1958 (first free: Lynn Hill 1993)",
    description: "The most famous big wall in the world. A true test of endurance, crack technique, and mental game. Every pitch is classic.",
    betaNotes: "Many parties take 3-5 days. Bring 2 sets of cams + lots of slings. Water is key.",
    lat: 37.7345,
    lng: -119.5328,
    stars: 4.9,
    starVotes: 1240,
    ticks: 187,
    difficultyColor: "purple",
    photoUrl: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80",
    photoUrls: [
      "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80",
      "https://picsum.photos/id/1016/800/600",
    ],
    hazards: "Rockfall, afternoon thunderstorms, long runouts on some pitches",
    bestConditions: "Cool spring or fall days. Avoid midday sun on the upper headwall.",
    sources: ["openbeta", "mountainproject"],
    lastUpdated: "2026-05-20",
  },
  {
    id: "r2",
    name: "Astroman",
    areaId: "yose",
    areaName: "Yosemite Valley",
    grade: "5.11c",
    type: "Trad",
    lengthFt: 1100,
    pitches: 11,
    protection: "Cams 0.3-3, nuts, RPs",
    fa: "Bridwell, Kauk, Long 1975",
    description: "Sustained, technical, and stunning. One of the best 5.11 crack climbs anywhere. The 'Astroman' corner is legendary.",
    betaNotes: "P1-3 are the crux. Bring doubles in small cams. Amazing position above the valley.",
    lat: 37.7398,
    lng: -119.5382,
    stars: 4.8,
    starVotes: 312,
    ticks: 94,
    difficultyColor: "red",
    photoUrl: "https://picsum.photos/id/1005/800/600",
    photoUrls: ["https://picsum.photos/id/1005/800/600"],
    bestConditions: "Late spring or early fall. Can be cold in shade.",
    sources: ["mountainproject"],
    lastUpdated: "2026-05-18",
  },
  // RED ROCKS
  {
    id: "r3",
    name: "Birdland",
    areaId: "redrocks",
    areaName: "Red Rock Canyon",
    grade: "5.7+",
    type: "Trad",
    lengthFt: 450,
    pitches: 4,
    protection: "Cams 0.5-3, nuts",
    fa: "Unknown",
    description: "The perfect first multi-pitch trad route in Red Rocks. Amazing views, great rock, and moderate climbing the whole way.",
    betaNotes: "Super classic. Bring a 70m rope. P3 has a fun chimney. Descend via rappel or walk-off.",
    lat: 36.1582,
    lng: -115.4461,
    stars: 4.7,
    starVotes: 892,
    ticks: 1340,
    difficultyColor: "yellow",
    photoUrl: "https://picsum.photos/id/1018/800/600",
    photoUrls: ["https://picsum.photos/id/1018/800/600", "https://picsum.photos/id/1033/800/600"],
    bestConditions: "Winter and spring. Can be hot in summer.",
    sources: ["openbeta", "mountainproject"],
    lastUpdated: "2026-05-10",
  },
  {
    id: "r4",
    name: "Solar Slab",
    areaId: "redrocks",
    areaName: "Red Rock Canyon",
    grade: "5.6",
    type: "Trad",
    lengthFt: 800,
    pitches: 7,
    protection: "Cams + nuts",
    fa: "Various",
    description: "Long, moderate, and incredibly fun. One of the best moderate multi-pitch climbs in the US. Perfect for new trad leaders.",
    betaNotes: "Start early – it's long. Great for practicing multi-pitch systems. Bring 1.5L water per person.",
    lat: 36.1421,
    lng: -115.4329,
    stars: 4.6,
    starVotes: 567,
    ticks: 2100,
    difficultyColor: "green",
    photoUrl: "https://picsum.photos/id/160/800/600",
    photoUrls: ["https://picsum.photos/id/160/800/600"],
    bestConditions: "Late fall through early spring.",
    sources: ["mountainproject"],
    lastUpdated: "2026-04-22",
  },
  // SQUAMISH
  {
    id: "r5",
    name: "The Grand Wall",
    areaId: "squamish",
    areaName: "Squamish",
    grade: "5.11a",
    type: "Trad",
    lengthFt: 1200,
    pitches: 10,
    protection: "Cams to #4, nuts, pins",
    fa: "Various 1960s-70s",
    description: "The crown jewel of Squamish. Incredible position, varied climbing, and the famous 'Split Pillar'. A must-do.",
    betaNotes: "Classic. The 'Sword' pitch is the crux for many. 70m rope recommended. Can be done in a long day.",
    lat: 49.6851,
    lng: -123.1378,
    stars: 4.9,
    starVotes: 445,
    ticks: 312,
    difficultyColor: "red",
    photoUrl: "https://picsum.photos/id/201/800/600",
    photoUrls: ["https://picsum.photos/id/201/800/600"],
    bestConditions: "July–September. Can seep early season.",
    sources: ["openbeta", "thecrag"],
    lastUpdated: "2026-05-19",
  },
  // FONTAINEBLEAU
  {
    id: "r6",
    name: "La Marie-Rose",
    areaId: "font",
    areaName: "Fontainebleau",
    grade: "V2",
    type: "Boulder",
    lengthFt: 12,
    fa: "Unknown (classic)",
    description: "The most famous boulder problem in the world. Perfect sandstone, iconic line, and the ultimate test of technique over power.",
    betaNotes: "Start left foot high, right hand undercling. The topout is the real crux. Pad + spotter essential.",
    lat: 48.4023,
    lng: 2.6891,
    stars: 4.8,
    starVotes: 2100,
    ticks: 8900,
    difficultyColor: "yellow",
    photoUrl: "https://picsum.photos/id/251/800/600",
    photoUrls: ["https://picsum.photos/id/251/800/600"],
    bestConditions: "Dry spring or fall. Avoid when wet (slippery!).",
    sources: ["openbeta", "thecrag"],
    lastUpdated: "2026-05-15",
  },
  {
    id: "r7",
    name: "L'Angle Allongé",
    areaId: "font",
    areaName: "Fontainebleau",
    grade: "V5",
    type: "Boulder",
    lengthFt: 14,
    fa: "Unknown",
    description: "A Font classic. Technical, powerful, and beautiful. One of the best V5s anywhere.",
    betaNotes: "High feet, precise hands. The 'allongé' move is a wild reach. Many strong climbers struggle here.",
    lat: 48.4155,
    lng: 2.7122,
    stars: 4.7,
    starVotes: 980,
    ticks: 3200,
    difficultyColor: "orange",
    photoUrl: "https://picsum.photos/id/29/800/600",
    photoUrls: ["https://picsum.photos/id/29/800/600"],
    bestConditions: "Cool, dry days. Great in winter too.",
    sources: ["thecrag"],
    lastUpdated: "2026-05-12",
  },
  // KALYMNOS
  {
    id: "r8",
    name: "Aphrodite",
    areaId: "kalymnos",
    areaName: "Kalymnos",
    grade: "6a+",
    type: "Sport",
    lengthFt: 85,
    pitches: 1,
    bolts: 12,
    protection: "12 bolts + anchor",
    fa: "Aris Theodoropoulos 1990s",
    description: "Incredible tufa climbing with sea views. The perfect introduction to Kalymnos sport climbing.",
    betaNotes: "Follow the beautiful tufas. A little pumpy for the grade. Amazing sunset spot.",
    lat: 36.9877,
    lng: 26.9321,
    stars: 4.6,
    starVotes: 1560,
    ticks: 4200,
    difficultyColor: "yellow",
    photoUrl: "https://picsum.photos/id/1006/800/600",
    photoUrls: ["https://picsum.photos/id/1006/800/600"],
    bestConditions: "April–June & September–October. Hot in summer.",
    sources: ["thecrag"],
    lastUpdated: "2026-05-20",
  },
  // INDIAN CREEK
  {
    id: "r9",
    name: "Supercrack",
    areaId: "indiancreek",
    areaName: "Indian Creek",
    grade: "5.10b",
    type: "Trad",
    lengthFt: 150,
    pitches: 1,
    protection: "Cams 0.5-2 (doubles ideal)",
    fa: "Earl Wiggins 1970s",
    description: "The most perfect splitter crack in the world. 150ft of flawless hands. The gold standard for crack climbing.",
    betaNotes: "Tape up. Hands the whole way – no feet needed if you're solid. One of the best 5.10s on Earth.",
    lat: 38.0233,
    lng: -109.5481,
    stars: 4.9,
    starVotes: 780,
    ticks: 1650,
    difficultyColor: "orange",
    photoUrl: "https://picsum.photos/id/133/800/600",
    photoUrls: ["https://picsum.photos/id/133/800/600"],
    bestConditions: "Spring and fall. Can be 100°F+ in summer.",
    sources: ["openbeta", "mountainproject"],
    lastUpdated: "2026-05-08",
  },
  {
    id: "r10",
    name: "The Incredible Hand Crack",
    areaId: "indiancreek",
    areaName: "Indian Creek",
    grade: "5.10a",
    type: "Trad",
    lengthFt: 120,
    pitches: 1,
    protection: "Cams #1-2.5",
    fa: "Unknown",
    description: "Another Creek classic. Perfect hands, great rock, and a fun roof at the top. Pure joy.",
    betaNotes: "Bring 3-4 #2 cams. The roof is easier than it looks. Classic Creek 5.10.",
    lat: 38.0199,
    lng: -109.5512,
    stars: 4.8,
    starVotes: 920,
    ticks: 2100,
    difficultyColor: "yellow",
    photoUrl: "https://picsum.photos/id/180/800/600",
    photoUrls: ["https://picsum.photos/id/180/800/600"],
    bestConditions: "March–May, September–November.",
    sources: ["mountainproject"],
    lastUpdated: "2026-05-01",
  },
  // More routes for density (Smith, Eldo, etc. abbreviated for prototype)
  {
    id: "r11",
    name: "To Bolt or Not to Be",
    areaId: "redrocks",
    areaName: "Red Rock Canyon",
    grade: "5.12b",
    type: "Sport",
    lengthFt: 110,
    bolts: 8,
    fa: "Randy Leavitt 1980s",
    description: "The famous overhanging arete. One of the best hard sport routes in Red Rocks. Powerful and technical.",
    betaNotes: "Big moves on good holds. Crux is the bulge. Bring a stick clip for the first bolt.",
    lat: 36.1611,
    lng: -115.4523,
    stars: 4.7,
    starVotes: 340,
    ticks: 420,
    difficultyColor: "red",
    photoUrl: "https://picsum.photos/id/1015/800/600",
    photoUrls: ["https://picsum.photos/id/1015/800/600"],
    bestConditions: "Winter and spring. Shaded in morning.",
    sources: ["openbeta"],
    lastUpdated: "2026-05-14",
  },
  {
    id: "r12",
    name: "The Pearl",
    areaId: "squamish",
    areaName: "Squamish",
    grade: "5.11d",
    type: "Trad",
    lengthFt: 350,
    pitches: 3,
    protection: "Cams + small wires",
    fa: "Various",
    description: "Sustained, beautiful, and exposed. One of Squamish's proudest lines. Amazing granite.",
    betaNotes: "P2 is the money pitch. Small gear helpful. Incredible exposure over the highway.",
    lat: 49.6899,
    lng: -123.1411,
    stars: 4.8,
    starVotes: 198,
    ticks: 87,
    difficultyColor: "red",
    photoUrl: "https://picsum.photos/id/251/800/600",
    photoUrls: ["https://picsum.photos/id/251/800/600"],
    bestConditions: "Summer. Can be wet in spring.",
    sources: ["thecrag"],
    lastUpdated: "2026-05-17",
  },
];

export const DEMO_USER: User = {
  id: "u1",
  name: "Alex Rivera",
  username: "@alexsends",
  location: "Boulder, CO",
  avatarUrl: "https://picsum.photos/id/1005/128/128",
  memberSince: "March 2024",
  totalSends: 87,
  hardestSend: "5.12a / V6",
  favoriteCrag: "Indian Creek",
  ticks: [],
  wishlist: ["r1", "r5"],
};

export const SPONSORS: Sponsor[] = [
  { name: "Petzl", logo: "🪢", url: "https://petzl.com", tier: "Founding", blurb: "Safety & innovation since 1975" },
  { name: "Black Diamond", logo: "💎", url: "https://blackdiamondequipment.com", tier: "Founding", blurb: "Climbing gear that inspires" },
  { name: "La Sportiva", logo: "🥾", url: "https://lasportiva.com", tier: "Supporting", blurb: "Footwear for the vertical world" },
  { name: "REI", logo: "🏕️", url: "https://rei.com", tier: "Supporting", blurb: "Co-op supporting outdoor communities" },
  { name: "Arc'teryx", logo: "🏔️", url: "https://arcteryx.com", tier: "Gear", blurb: "Technical apparel & packs" },
];

export const MOCK_CONDITIONS = [
  { id: "c1", routeId: "r1", user: "Sam C.", date: "2026-05-18", text: "Dry and perfect. The upper headwall was bomber.", emoji: "☀️" },
  { id: "c2", routeId: "r3", user: "Priya K.", date: "2026-05-19", text: "A bit sandy on P2 but overall excellent. Great for new leaders.", emoji: "🌵" },
];

// Helper: get grade color class
export function getGradeClass(color: string): string {
  if (color === "green") return "bg-emerald-500 text-white";
  if (color === "yellow") return "bg-amber-500 text-white";
  if (color === "orange") return "bg-orange-500 text-white";
  if (color === "red") return "bg-red-500 text-white";
  return "bg-violet-600 text-white";
}
